/*
 * Scheduler service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// TODO rename to CustomerId
type SlotsRequest struct {
	ClientId string `json:"client_id,omitempty"`

	Slots []Slot `json:"slots,omitempty"`
}
