/*
 * Scheduler service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Slot struct {
	ClientId string `json:"client_id,omitempty"`

	TpStart time.Time `json:"tp_start,omitempty"`

	Len int32 `json:"len,omitempty"`
}
