package holidays

import (
	"time"

	common "scheduler/appointment-service/internal"
)

var holiday []Holiday

func init() {
	type Interval = common.Interval

	// Autogenerated code
	holiday = []Holiday{
		{
			Description: "New Year",
			Interval: Interval{
				Start: time.Date(2024, time.January, 1, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.January, 2, 23, 59, 59, 0, time.UTC),
			},
		},
		{
			Description: "International Women’s Day",
			Interval: Interval{
				Start: time.Date(2024, time.March, 8, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.March, 8, 23, 59, 59, 0, time.UTC),
			},
		},
		{
			Description: "Nauryz",
			Interval: Interval{
				Start: time.Date(2024, time.March, 21, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.March, 25, 23, 59, 59, 0, time.UTC), // Shift to Monday if March 23 falls on a Saturday
			},
		},
		{
			Description: "Kazakhstan's People Solidarity Holiday",
			Interval: Interval{
				Start: time.Date(2024, time.May, 1, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.May, 1, 23, 59, 59, 0, time.UTC),
			},
		},
		{
			Description: "Defenders’ Day",
			Interval: Interval{
				Start: time.Date(2024, time.May, 7, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.May, 8, 23, 59, 59, 0, time.UTC), // Shift if May 4 falls on a Saturday
			},
		},
		{
			Description: "Victory Day",
			Interval: Interval{
				Start: time.Date(2024, time.May, 9, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.May, 9, 23, 59, 59, 0, time.UTC),
			},
		},
		{
			Description: "Capital Day",
			Interval: Interval{
				Start: time.Date(2024, time.July, 6, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.July, 8, 23, 59, 59, 0, time.UTC), // Shift to Monday if July 6 falls on a Saturday
			},
		},
		{
			Description: "Constitution Day of the RK",
			Interval: Interval{
				Start: time.Date(2024, time.August, 30, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.August, 30, 23, 59, 59, 0, time.UTC),
			},
		},
		{
			Description: "Republic Day",
			Interval: Interval{
				Start: time.Date(2024, time.October, 25, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.October, 25, 23, 59, 59, 0, time.UTC),
			},
		},
		{
			Description: "Kazakhstan Independence Day",
			Interval: Interval{
				Start: time.Date(2024, time.December, 16, 0, 0, 0, 0, time.UTC),
				End:   time.Date(2024, time.December, 16, 23, 59, 59, 0, time.UTC),
			},
		},
	}
}

func getKzHolidays() common.Intervals {
	out := make(common.Intervals, len(holiday))
	for i, h := range holiday {
		out[i] = h.Interval
	}
	return out
}

func KzHolidaysProducer() common.IntervalsProducer {
	return common.GetIntervalsFunc(getKzHolidays)
}
