/*
 * Scheduler service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"log/slog"
	"net/http"

	server "scheduler/appointment-service/api"

	"scheduler/appointment-service/internal/storage"

	"github.com/jmoiron/sqlx"
	_ "github.com/mattn/go-sqlite3"
)

func main() {
	log.Printf("Server started")

	dbPath := "tmp_test.db" //TODO remove

	db, err := sqlx.Open("sqlite3", dbPath)
	if err != nil {
		slog.Error(err.Error())
	}
	defer db.Close()

	storage := storage.Storage{DB: db}
	router := server.NewRouter(&storage)

	log.Fatal(http.ListenAndServe(":8080", router))
}
