openapi: 3.0.0
info:
  title: "Scheduler service"
  version: "0.1"
paths:
  /slots/{business_id}:
    get:
      summary: Available time slots
      tags:
        - Time slots
      parameters: 
        - name: business_id
          in: path
          required: true
          schema:
            type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        - name: date_start
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: date_end
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableSlots'
        'default':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Try to register time slot(s)
      tags:
        - Time slots
      parameters: 
        - name: business_id
          in: path
          required: true
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        content:
          'application/json':
            schema:
                $ref: '#/components/schemas/SlotsRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                properties:
                  query_id:
                    type: string
                    example: "550e8400-e29b-41d4-a716-446655440000"
        'default':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Slot:
      properties:
        tp_start:
          type: string
          format: date-time
        len:
          type: integer
    SlotsRequest:
      properties:
        client_id:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        slots:
            type: array
            items:
                  $ref: '#/components/schemas/Slot'
    AvailableSlots:
      properties:
        query_id:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        slots:
          type: array
          items:
                $ref: '#/components/schemas/Slot'
    Error:
      properties:
        query_id:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        description:
          type: string
        code:
          type: integer
  