openapi: 3.0.0
info:
  title: "Scheduler service"
  version: "0.1"
paths:
  /slots/{customerId}:
    get:
      summary: Available time slots
      tags:
        - Time slots
      parameters: 
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        - name: date_start
          in: header
          required: true
          schema:
            type: string
            format: date
        - name: date_end
          in: header
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Slot'
components:
  schemas:
    Slot:
      properties:
        tp_start:
          type: string
          format: date-time
        tp_end:
          type: string
          format: date-time
       
    